apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-ingress
  namespace: app
spec:
  ingressClassName: nginx
  rules:
  - host: echo.app
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: echoserver
            port:
              number: 8088
