apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd-platform
spec:
  project: default

  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  
  source:
    repoURL: https://github.com/cuonghv00/monitor-kong-gw.git
    targetRevision: HEAD
    path: servicemonitor